// Generated by CoffeeScript 1.8.0
(function() {
  define(["backbone", "marionette"], function(Backbone, Marionette) {
    return Backbone.Marionette.AppRouter.extend({
      appRoutes: {
        "": "index"
      }
    });
  });

}).call(this);
