// Generated by CoffeeScript 1.8.0
(function() {
  define(["jquery", "hbs!templates/desktopHeader", "backbone", "marionette"], function($, template, Backbone) {
    return Backbone.Marionette.ItemView.extend({
      template: template
    });
  });

}).call(this);
