// Generated by CoffeeScript 1.8.0
(function() {
  define(["backbone", "marionette", "jquery", "jquerymobile", "hbs!templates/mobileHeader"], function(Backbone, Marionette, $, jqm, template) {
    return Backbone.Marionette.ItemView.extend({
      template: template({
        initialize: function() {
          return _.bindAll(this);
        },
        onRender: function() {
          this.$el.navbar();
        }
      })
    });
  });

}).call(this);
