// Generated by CoffeeScript 1.8.0
(function() {
  define(['App', 'backbone', 'marionette', 'jquery', 'models/Model', 'hbs!templates/welcome'], function(App, Backbone, Marionette, $, Model, template) {
    return Backbone.Marionette.ItemView.extend({
      template: template,
      model: new Model({
        mobile: App.mobile
      }),
      events: {}
    });
  });

}).call(this);
