// Generated by CoffeeScript 1.8.0
(function() {
  require.config({
    baseUrl: AJANPLUGINPATH + "js/app",
    paths: {
      jquery: "../libs/jquery",
      jqueryui: AJANPLUGINPATH + "js/libs/jqueryui",
      jquerymobile: "../libs/jquery.mobile",
      underscore: "../libs/lodash",
      backbone: "../libs/backbone",
      marionette: "../libs/backbone.marionette",
      handlebars: "../libs/handlebars",
      hbs: "../libs/hbs",
      i18nprecompile: "../libs/i18nprecompile",
      json2: "../libs/json2",
      jasmine: "../libs/jasmine",
      "jasmine-html": "../libs/jasmine-html",
      "backbone.validateAll": AJANPLUGINPATH + "js/libs/plugins/Backbone.validateAll",
      bootstrap: AJANPLUGINPATH + "js/libs/plugins/bootstrap",
      text: "../libs/plugins/text",
      jasminejquery: "../libs/plugins/jasmine-jquery"
    },
    shim: {
      bootstrap: ["jquery"],
      jqueryui: ["jquery"],
      jquerymobile: ["jqueryui"],
      backbone: {
        deps: ["underscore", "jquery"],
        exports: "Backbone"
      },
      marionette: {
        deps: ["underscore", "backbone", "jquery"],
        exports: "Marionette"
      },
      handlebars: {
        exports: "Handlebars"
      },
      "backbone.validateAll": ["backbone"],
      jasmine: {
        exports: "jasmine"
      },
      "jasmine-html": {
        deps: ["jasmine"],
        exports: "jasmine"
      }
    },
    hbs: {
      templateExtension: "html",
      helperDirectory: "templates/helpers/",
      i18nDirectory: "templates/i18n/",
      compileOptions: {}
    }
  });

}).call(this);
