// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['startapp', 'backbone'], function(App) {
    return App.module("Entities.Comment", function(Comment, App) {
      var CommentModel, commentCollection;
      CommentModel = (function(_super) {
        __extends(CommentModel, _super);

        function CommentModel() {
          return CommentModel.__super__.constructor.apply(this, arguments);
        }

        CommentModel.prototype.idAttribute = 'ID';

        CommentModel.prototype.defaults = {
          user_id: "",
          component: "",
          type: "",
          action: "",
          content: "",
          item_id: "",
          secondary_item_id: "",
          date_recorded: "",
          comment_count: "",
          nonce: ACTIVITY_NONCE_STRING
        };

        CommentModel.prototype.name = 'comment';

        CommentModel.prototype.urlRoot = function() {
          return SITEURL + ajan_post_comments_uri;
        };

        return CommentModel;

      })(Backbone.Model);
      Comment.CommentCollection = (function(_super) {
        __extends(CommentCollection, _super);

        function CommentCollection() {
          return CommentCollection.__super__.constructor.apply(this, arguments);
        }

        CommentCollection.prototype.model = CommentModel;

        CommentCollection.prototype.url = function() {
          return SITEURL + ajan_get_comments_uri;
        };

        CommentCollection.prototype.parse = function(response) {
          return response.collection;
        };

        return CommentCollection;

      })(Backbone.Collection);
      return commentCollection = new Comment.CommentCollection;
    });
  });

}).call(this);
