// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['startapp', 'backbone'], function(App) {
    return App.module("Entities.User", function(User, App) {
      var UserModel, userCollection;
      UserModel = (function(_super) {
        __extends(UserModel, _super);

        function UserModel() {
          return UserModel.__super__.constructor.apply(this, arguments);
        }

        UserModel.prototype.idAttribute = 'ID';

        UserModel.prototype.defaults = {
          ID: "",
          name: "",
          profile_pic: "",
          profile_url: ""
        };

        UserModel.prototype.name = 'user';

        return UserModel;

      })(Backbone.Model);
      User.UserCollection = (function(_super) {
        __extends(UserCollection, _super);

        function UserCollection() {
          return UserCollection.__super__.constructor.apply(this, arguments);
        }

        UserCollection.prototype.model = UserModel;

        UserCollection.prototype.url = function() {
          return SITEURL + '/api/users';
        };

        UserCollection.prototype.parse = function(response) {
          return response.collection;
        };

        return UserCollection;

      })(Backbone.Collection);
      return userCollection = new User.UserCollection;
    });
  });

}).call(this);
