// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['startapp', 'backbone'], function(App) {
    return App.module("Entities.User", function(Activity, App) {
      var API, ActivityCollection, User, activityCollection, myarray;
      User = (function(_super) {
        __extends(User, _super);

        function User() {
          return User.__super__.constructor.apply(this, arguments);
        }

        User.prototype.idAttribute = 'ID';

        User.prototype.defaults = {
          ID: "",
          name: "",
          profile_pic: "",
          profile_url: ""
        };

        User.prototype.name = 'activity';

        return User;

      })(Backbone.Model);
      ActivityCollection = (function(_super) {
        __extends(ActivityCollection, _super);

        function ActivityCollection() {
          return ActivityCollection.__super__.constructor.apply(this, arguments);
        }

        ActivityCollection.prototype.model = Activity;

        ActivityCollection.prototype.url = function() {
          return SITEURL + ajan_get_activities_uri;
        };

        return ActivityCollection;

      })(Backbone.Collection);
      activityCollection = new ActivityCollection;
      myarray = [];
      activityCollection.fetch();
      API = {
        getActivities: function() {
          return activityCollection;
        }
      };
      return App.reqres.setHandler("get:activity:collection", function(data) {
        return API.getActivities();
      });
    });
  });

}).call(this);
