// Generated by CoffeeScript 1.8.0
(function() {
  require(["App", "routers/AppRouter", "controllers/DesktopController", "jquery", "backbone", "marionette", "jqueryui", "bootstrap", "backbone.validateAll"], function(App, AppRouter, AppController) {
    console.log("controller");
    App.appRouter = new AppRouter({
      controller: new AppController()
    });
    App.start();
  });

}).call(this);
