// Generated by CoffeeScript 1.8.0
(function() {
  require(["App", "jquery", "routers/AppRouter", "controllers/MobileController", "backbone", "marionette", "jquerymobile", "backbone.validateAll"], function(App, $, AppRouter, AppController) {
    $.mobile.linkBindingEnabled = false;
    $.mobile.hashListeningEnabled = false;
    App.appRouter = new AppRouter({
      controller: new AppController()
    });
    App.start();
  });

}).call(this);
