// Generated by CoffeeScript 1.8.0
(function() {
  define(["App", "backbone", "marionette", "views/WelcomeView", "views/DesktopHeaderView"], function(App, Backbone, Marionette, WelcomeView, DesktopHeaderView) {
    return Backbone.Marionette.Controller.extend({
      initialize: function(options) {
        console.log("in controller");
        App.discussionRegion.show(new WelcomeView());
      },
      index: function() {}
    });
  });

}).call(this);
