// Generated by CoffeeScript 1.8.0
(function() {
  define(["App", "backbone", "marionette", "views/WelcomeView", "views/MobileHeaderView"], function(App, Backbone, Marionette, WelcomeView, MobileHeaderView) {
    return Backbone.Marionette.Controller.extend({
      initialize: function(options) {
        App.headerRegion.show(new MobileHeaderView());
      },
      index: function() {
        App.mainRegion.show(new WelcomeView());
      }
    });
  });

}).call(this);
