// Generated by CoffeeScript 1.8.0
(function() {
  define(["jquery", "backbone", "marionette", "underscore", "handlebars"], function($, Backbone, Marionette, _, Handlebars) {
    var App, isMobile;
    isMobile = function() {
      var userAgent;
      userAgent = navigator.userAgent || navigator.vendor || window.opera;
      return /iPhone|iPod|iPad|Android|BlackBerry|Opera Mini|IEMobile/.test(userAgent);
    };
    App = new Backbone.Marionette.Application();
    App.addRegions({
      discussionRegion: discussion_container
    });
    App.addInitializer(function() {
      Backbone.history.start();
    });
    App.mobile = isMobile();
    return App;
  });

}).call(this);
